import { Link } from "react-router-dom";
import StudyGuideShell from "../courses/StudyGuideShell";
import { GuideMcqSection } from "../../components/GuideMcq";
import { useProgress } from "../../context/ProgressContext";
import { TheoryBox, WorkedExample } from "./LaBlocks";
import { LA_TENSOR_PRODUCTS_QUIZ } from "../../data/laQuizzes";

export default function TensorProductsGuide({ embedded = false }) {
  const { saveQuizScore } = useProgress();
  const content = (
    <div className={embedded ? "la-topic-content" : "main"}>
      {!embedded && <h1>Tensor Products &amp; Kronecker Products</h1>}
      <p>Review <Link to="/linear-algebra/abstract-linear-algebra/1">dual spaces and linear functionals</Link> and <Link to="/linear-algebra/matrices/1">matrix operations</Link>. Fix the basis order and vectorization convention before doing coordinate calculations.</p>
      <section className="section" id="tensor-products-section-1">
        <h2 className="sec-title">Tensor products turn bilinear maps into linear maps</h2>
        <TheoryBox title={"Start with bilinearity"}>
          <p>{"Let V and W be finite-dimensional vector spaces over the same field $\\mathbb F$. A map $b:V\\times W\\to U$ is bilinear when it is linear in either argument while the other is fixed. For example, multiplying one coordinate from each input is bilinear, but generally not linear as a map on the pair considered as one direct-sum vector."}</p>
          <p>{"The tensor product $V\\otimes W$ is generated by symbols $v\\otimes w$ subject to $(v+v\\prime)\\otimes w=v\\otimes w+v\\prime\\otimes w$, $v\\otimes(w+w\\prime)=v\\otimes w+v\\otimes w\\prime$, and $(av)\\otimes w=v\\otimes(aw)=a(v\\otimes w)$. Applying a scalar to both factors therefore contributes its square."}</p>
        </TheoryBox>
        <TheoryBox title={"The universal property"}>
          <p>{"For every bilinear b there is a unique linear map $\\widetilde b:V\\otimes W\\to U$ with $\\widetilde b(v\\otimes w)=b(v,w)$. The bilinear relations ensure that different equivalent expansions give the same result. This is the purpose of the tensor product: it packages two linear inputs into one linear domain."}</p>
          <p>{"A pure or simple tensor has the form $v\\otimes w$. General tensors are sums of such terms. Not every tensor is a single pure tensor. Also $V\\otimes W$ differs from $V\\oplus W$: their dimensions are generally a product and a sum, respectively."}</p>
        </TheoryBox>
      </section>
      <section className="section" id="tensor-products-section-2">
        <h2 className="sec-title">Bases and simple tensors</h2>
        <TheoryBox title={"An ordered product basis"}>
          <p>{"If $(e_1,\\ldots,e_m)$ and $(f_1,\\ldots,f_n)$ are bases, the $mn$ tensors $e_i\\otimes f_j$ form a basis of $V\\otimes W$. Use the order $(e_1\\otimes f_1,\\ldots,e_1\\otimes f_n,e_2\\otimes f_1,\\ldots,e_m\\otimes f_n)$. Then $\\dim(V\\otimes W)=mn$."}</p>
          <p>{"For $v=\\sum_i v_ie_i$ and $w=\\sum_jw_jf_j$, bilinearity gives $v\\otimes w=\\sum_{i,j}v_iw_j(e_i\\otimes f_j)$. The coefficient array of a pure tensor is the outer product $vw^T$. Conversely, a nonzero two-factor tensor is pure exactly when its coefficient matrix has rank one."}</p>
        </TheoryBox>
        <TheoryBox title={"Swapping factors requires a map"}>
          <p>{"There is a natural flip isomorphism $v\\otimes w\\mapsto w\\otimes v$, but these expressions belong to differently ordered tensor product spaces. Coordinate arrays generally require a permutation when factors are swapped. Do not treat the tensor or Kronecker product as ordinary commutative multiplication."}</p>
          <p>{"If $A:V\\to V\\prime$ and $B:W\\to W\\prime$ are linear, the map $A\\otimes B$ is defined on pure tensors by $(A\\otimes B)(v\\otimes w)=Av\\otimes Bw$ and extends linearly to sums."}</p>
        </TheoryBox>
      </section>
      <section className="section" id="tensor-products-section-3">
        <h2 className="sec-title">The Kronecker product is the coordinate matrix</h2>
        <TheoryBox title={"Block construction and sizes"}>
          <p>{"For an $m\\times n$ matrix A and a $p\\times q$ matrix B, $A\\otimes B$ is an $mp\\times nq$ block matrix whose block (i,j) is $a_{ij}B$. Under the ordered product bases above, it represents the tensor product of the two linear maps."}</p>
          <p>{"Distinguish the products: AB is ordinary matrix multiplication; entrywise multiplication needs equal shapes; $A\\otimes B$ expands every scalar entry of A into a whole scaled copy of B. A zero entry creates an entire zero block."}</p>
        </TheoryBox>
        <TheoryBox title={"Rules with compatible dimensions"}>
          <p>{"The mixed-product identity is $(A\\otimes B)(C\\otimes D)=(AC)\\otimes(BD)$ whenever AC and BD are defined. Transpose respects the factors: $(A\\otimes B)^T=A^T\\otimes B^T$. If A and B are square and invertible, $(A\\otimes B)^{-1}=A^{-1}\\otimes B^{-1}$."}</p>
          <p>{"Rank multiplies: $\\operatorname{rank}(A\\otimes B)=\\operatorname{rank}(A)\\operatorname{rank}(B)$. For square A of size m and B of size p, $\\det(A\\otimes B)=\\det(A)^p\\det(B)^m$ and $\\operatorname{tr}(A\\otimes B)=\\operatorname{tr}(A)\\operatorname{tr}(B)$. Check the exponents and dimensions before applying these formulas."}</p>
          <p>{"If $Av=\\lambda v$ and $Bw=\\mu w$ with nonzero vectors, then $(A\\otimes B)(v\\otimes w)=\\lambda\\mu(v\\otimes w)$. Eigenvalue products arise from tensoring the eigenvector directions."}</p>
        </TheoryBox>
      </section>
      <section className="section" id="tensor-products-section-4">
        <h2 className="sec-title">Vectorization and applications</h2>
        <TheoryBox title={"State the stacking convention first"}>
          <p>{"Here $\\operatorname{vec}(X)$ stacks the columns of X from left to right. If A is $m\\times n$, X is $n\\times p$ and B is $p\\times q$, then $\\operatorname{vec}(AXB)=(B^T\\otimes A)\\operatorname{vec}(X)$. The right-hand matrix is $mq\\times np$, matching the output and input vector lengths."}</p>
          <p>{"The transpose on B comes from column stacking, not from an inverse or an inner product. With row stacking the formula changes. For column vectors u and v, $\\operatorname{vec}(uv^T)=v\\otimes u$; reversing those factors without changing the ordering is a common error."}</p>
        </TheoryBox>
        <TheoryBox title={"Use structure instead of materializing a huge matrix"}>
          <p>{"Tensor products describe separable transformations, grid operators and combined coordinate systems. A Kronecker matrix can be enormous even if its two factors are small. When applicable, the vectorization identity lets you reshape a vector, apply smaller matrix products, and stack the result without explicitly storing every block."}</p>
          <p>{"The Kronecker sum $A\\otimes I_p+I_m\\otimes B$, for square factors of sizes m and p, acts on a tensor eigenvector with eigenvalue $\\lambda+\\mu$, whereas the Kronecker product gives $\\lambda\\mu$. Keep product and sum formulas distinct."}</p>
          <p>{"For a matrix equation $AX+XB=C$ with square factors, column stacking gives $(I\\otimes A+B^T\\otimes I)\\operatorname{vec}(X)=\\operatorname{vec}(C)$ with appropriately sized identities. This is a modeling identity, not a recommendation to form a dense inverse."}</p>
        </TheoryBox>
      </section>
      <section className="section" id="tensor-products-examples">
        <h2 className="sec-title">Worked examples</h2>
        <WorkedExample number={1} title={"Expand a pure tensor"} setup={"Let $u=(1,2)^T$ and $v=(3,-1)^T$."}
          steps={["In the ordered product basis the coefficients are $1\\cdot3$, $1\\cdot(-1)$, $2\\cdot3$, $2\\cdot(-1)$.", "Thus $u\\otimes v=(3,-1,6,-2)^T$.", "The coefficient array $uv^T=\\begin{pmatrix}3&-1\\\\6&-2\\end{pmatrix}$ has its second row twice its first."]}
          result={"The tensor is pure with coefficient matrix rank 1."} check={"The determinant is $-6+6=0$ and the matrix is nonzero."} mistake={"Our tensor basis lists j fastest; column vectorization of the outer product uses a different ordering."} />
        <WorkedExample number={2} title={"Build a Kronecker block matrix"} setup={"Let $A=\\begin{pmatrix}1&2\\\\0&-1\\end{pmatrix}$ and $B=\\begin{pmatrix}2&0\\\\1&3\\end{pmatrix}$."}
          steps={["Build four blocks: $B$, $2B$, $0B$, and $-B$.", "$A\\otimes B=\\begin{pmatrix}2&0&4&0\\\\1&3&2&6\\\\0&0&-2&0\\\\0&0&-1&-3\\end{pmatrix}$.", "Each factor is two by two, so the result is four by four."]}
          result={"The bottom-left block is a two-by-two zero matrix."} check={"The determinant formula gives $(-1)^2\\,6^2=36$."} mistake={"A scalar zero in A becomes a whole zero block, not one zero entry."} />
        <WorkedExample number={3} title={"Apply two maps independently"} setup={"Take $A=\\operatorname{diag}(2,3)$, $B=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$, $u=(1,2)^T$ and $v=(3,4)^T$."}
          steps={["$Au=(2,6)^T$ and $Bv=(7,4)^T$.", "$Au\\otimes Bv=(14,8,42,24)^T$.", "The input tensor is $(3,4,6,8)^T$, and multiplication by the block diagonal matrix with blocks $2B$ and $3B$ gives the same result."]}
          result={"$(A\\otimes B)(u\\otimes v)=(14,8,42,24)^T$."} check={"The first two output entries come from 2B and the last two from 3B."} mistake={"Do not apply A and B to the same factor or interchange the factor order."} />
        <WorkedExample number={4} title={"Verify column vectorization"} setup={"Let $A=\\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}$, $X=\\begin{pmatrix}1&3\\\\2&4\\end{pmatrix}$ and $B=\\begin{pmatrix}2&0\\\\1&1\\end{pmatrix}$."}
          steps={["$AX=\\begin{pmatrix}5&11\\\\2&4\\end{pmatrix}$, then $AXB=\\begin{pmatrix}21&11\\\\8&4\\end{pmatrix}$.", "Column stacking gives $\\operatorname{vec}(X)=(1,2,3,4)^T$ and $\\operatorname{vec}(AXB)=(21,8,11,4)^T$.", "$B^T\\otimes A=\\begin{pmatrix}2&4&1&2\\\\0&2&0&1\\\\0&0&1&2\\\\0&0&0&1\\end{pmatrix}$; multiplying it by the input vector yields $(21,8,11,4)^T$."]}
          result={"The matrix calculation confirms $\\operatorname{vec}(AXB)=(B^T\\otimes A)\\operatorname{vec}(X)$."} check={"Both sides have four coordinates in the same column-stacking order."} mistake={"Using B instead of its transpose produces a different operator."} />
        <WorkedExample number={5} title={"A tensor that is not pure"} setup={"Consider $t=e_1\\otimes f_1+e_2\\otimes f_2$ in $\\mathbb R^2\\otimes\\mathbb R^2$."}
          steps={["Its coefficient matrix is $\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$.", "If $t=u\\otimes v$, that matrix would be the outer product $uv^T$ and have rank at most one.", "The identity matrix has rank two, a contradiction."]}
          result={"The tensor needs at least two pure terms, and the displayed expression uses exactly two."} check={"Its determinant is 1, so it cannot be a rank-one outer product."} mistake={"A sum of pure tensors is not necessarily pure."} />
      </section>
      <GuideMcqSection id="quiz-la-tensor-products-checkpoint" badge="Topic checkpoint · 20 questions"
        title="Tensor Products &amp; Kronecker Products" scoreId="score-la-tensor-products-checkpoint" section="la-tensor-products-checkpoint"
        questions={LA_TENSOR_PRODUCTS_QUIZ} onComplete={(score, total) => saveQuizScore("guide-mcq-la-tensor-products-checkpoint", score, total)} />
    </div>
  );
  if (embedded) return content;
  return <StudyGuideShell guideClass="partial-derivatives-guide" title="Tensor Products &amp; Kronecker Products">
    <nav className="sidebar" aria-label="Tensor Products &amp; Kronecker Products sections">
      <Link className="sb-link" to="/linear-algebra/overview#abstract-linear-algebra">Course overview</Link>
      <a className="sb-link" href="#tensor-products-section-1">Tensor products turn bilinear maps into linear maps</a>
      <a className="sb-link" href="#tensor-products-section-2">Bases and simple tensors</a>
      <a className="sb-link" href="#tensor-products-section-3">The Kronecker product is the coordinate matrix</a>
      <a className="sb-link" href="#tensor-products-section-4">Vectorization and applications</a>
      <a className="sb-link" href="#tensor-products-examples">Worked examples</a>
      <a className="sb-link" href="#quiz-la-tensor-products-checkpoint">Checkpoint</a>
    </nav>{content}
  </StudyGuideShell>;
}
